sopsAgeKeys: ENC[AES256_GCM,data:tGh7sG/dZ4iJvV787H1SfnMuDsp9174zQzPnHkpWMmdQQ2fpJ2+u2FV/lx4+1JJa49AXccpBht2n+dRY06HKPHHW3XO1gS0vsj6QQYegem/yIlez1QMNlOiIT0eZHonaQKQlUxUwr3aDZU9DIyAKTtjm95Bu6Cc4chr7dSoCuelVbzTn5P82jPrHxuSBf9zksLsVneRrtKy+VSnl5sV7tAS6t7p6peiVdlco9U1X6hM3WBiA7gR8Pfo67ac=,iv:LXhKpsKt3s2UKHUz5NLzI+9mrbn4Ui/Y1Pr1QUb33co=,tag:vX7vN0Qlbx744WD/pb9CpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aFp2RXpkazdRcTBWeWpK
            T1hSM2lOZkx6VnBzWjA5c1RVdU5qd3M5VkhFCnB4MnpkR01PL3FMSzBTMmdiSVVl
            Mk9GRG9BNmRlNnBKNGdWY0dZa2E0ZVUKLS0tIEpRcDJiVVN2UW1QanpyaTZSSVBM
            N2lwNDdDcklyQUZEa3c3TU5zSTNJY2MK5LEXTwTAjgVliQinorHn9aLwX/7L23+A
            F6teA8NLJf1b+4D+PBQ0/mNraKavgAC/Du/VBY78TcRrr2ELuAvAXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cp8rnfn8efvd6z9p3glwhgdh22q8vmw8y63hf7q702ahsc5lc50qsvv4su
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQitXRzh6b0laRW40Skpp
            dWczWEhkdWZyZTBlNEVON3FjMXlscUR3L2dnCkFHSjUzWnovbnU4RGJtOUVLamtP
            VFJ2QXlVMlZCa3hCb21UUktLWC9PK2MKLS0tIGNYR3plcGd5RHplMU04cjZtVjN4
            YlVhZkNFcmVnOUdJUkUvQ0RxRFRHTU0KBxTS1dwuLq6Sw00bptKMszKeXcpMfEDA
            P1/VWcN5gFo3IflLIvjpFsthO+YhUcNUUpZriBssd4Sj4sVxrMslpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycHBjSkM0YlNGdXl4SnZa
            dGY5V1dOdHkrZVRBeGozVWlwVzJkY3FvZVUwCnh5TnI4dnYwbis3MEF3WTlIN3Bu
            a2pGRTA4Y1YyWUZ3Y0JxYXgxU3dxaFkKLS0tIFZCeUtmQjc3RjVVNGxUdWwwMUZZ
            SlkvSGVTYS9nWVk3NUZ1QnVmdStRQzgKv8VmnN43kz0pzvtLrS1V+z5IOODmnx3l
            LNZYbeOJSV1u93/uRopQEnxcTe5HmfpczI5Gb1AzTmWL0W1fCJX4JA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18xn7rqxu27kschgqs7u5x7af9evnpcp4sru34th6zhhwlwnwycpsajeeh9
    lastmodified: "2026-08-21T11:50:39Z"
    mac: ENC[AES256_GCM,data:bZvGzIvdj6pgZtVsHPFPCRgRTs43ackNjkezkEEdt6szj1u+KJeFubI4wDa/ZpkNk5plKwZD7CgcdEkSAn85IJWu+jf15gJ3AdHeB4XO8mvEWDxRW6kmp56dcFATXDpUlD9c1WzO+caiyfgFEZ3SXPUKTz07tHZCPnb90OlEVAk=,iv:1wpQ6kUO+KJ1EvaBflV/5fIRXR+gSc+sPuuRP59E/LA=,tag:RaqMeSOSd+IKgQpMVzpBbA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
