sopsAgeKeys: ENC[AES256_GCM,data:qq+voZvam7Yua0yvfNaysoGnD/nD29vqqp2oKJ3NsagnZ6CSs62AcfOaATq1z6fIdPYvkNUVqWIFWrWM6Sbq9dIT2B0dYnm1JFqcNW0zg/U7vCHjgdM2uYFxD4lpjiNErKXi1J3h6xPwregbODnV0hCQuskvl84DBqwaR4w1YaYxtJ5DoebZ8TmCAY+qsj6n0YuqyFbdOjeJz8t/GkaSzVPxDIVzfDRmhvPMe6zmCHMDl5t2GKy3O4jCtnU=,iv:wmeBq4tTaKMMnEj0mlDr+xWl0s4i15MSAdUn5hRRRVk=,tag:im9o+7lGZb7fuyEAlJVmKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VkU5VXJxblJaYkVkb2N0
            Wmk5c3kwNkk5aDVxNkdNSXdhL1htRThTZncwCnplcDdDSlI3OEZiRnFaNklYQjVt
            RElYWmc3aHA1UEtHd0x4clo5ZU93dU0KLS0tIGVDWUY2SWpjLytaaGpEakFVWmdK
            eHc3RHZJd0U5dEFPUTYwNEdHd1pRT3cKEYlgJorHLj55Kl9SPPnZIEJCJ5cCzqDT
            cXhxz3IezbOej9gbSuNGAy2Ih+PYpqoVT1iv2/etzFb88e8fNK5Brg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1elr3rr7cmcghxycewyevsx0gr0u3r97npkfg7sxsmugs7a3lzymq3pxc8t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdGt5WVVDdXhpVC9mQWF6
            MVJtNEw3bXRzbno3SmY2djFLREFObzdPcEF3CnI1c2I0UGtVRXJkNTJWMTBlWFNx
            NWlRa1gvZ3lMQTRVMGoydjZiT0xDdEEKLS0tIDU1dGpES2s2TDBoalU2MU43emRq
            QWw2dGtMQ3RNbSs5UXArdUFiSGxzQzAKGqx+R1Iw9G6GmG0+6fHqSt6zRUZWvCl+
            w0WAu++j9biNlP8ImNkyTfCR7fKDNYqNkdo0rPnr1x0hnI9gApO1Qg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQmJINC9BZG1PSlhVVEJa
            bUFLbXNyYWlSeDhTYXVTRCtsTmlsQm10ZzNZCmczT3BPL3YzeTJ6UFhHUWxaelpC
            ZlVxV203TkwzbjNlSEw5KzZIa0NranMKLS0tIFY3MDlTd1VIWGo1eEhaOFpQNnEr
            cXRwTzFrUnNXL1JybURTTGlzc3pMSjQK6uuz5i54rD785CvvkKR/AsHDlBiVimzR
            cPjslTVdTEYUbR2dm6EiHZM3GmpTouI/kEsudfEJfAhCwpXpHPbuww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18xn7rqxu27kschgqs7u5x7af9evnpcp4sru34th6zhhwlwnwycpsajeeh9
    lastmodified: "2026-09-09T06:33:13Z"
    mac: ENC[AES256_GCM,data:4cC0dvgpJPIRe//U7plFzpf4nIG9VWKBpHRLaoQEr0NSGvuZi7iwInYSxuM4BdRUVJvZRuUtldcdUgn/rM0Eex2RQyA1xYpqgeHAUcoc3P60fEA0dG0O/3SPHRJWlA7hfGgw5UTucUDBybQfuOjw/0K8UDKKTlWyjOBSGkfKNPQ=,iv:UHjfcM8fGLoJfq4kefi6PkLC1yfylbiXxZrN95aCGmo=,tag:w+pfGo/0TxbmXTTnDC8Y8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
