sopsAgeKeys: ENC[AES256_GCM,data:zx0okMjClLp3AADmtMDudTpN/9ClXd+pawwMtxG1tHD47rzZPkpHtwt08VytRt5YZHsdpDeG5OzlFGbfd39AMteE7CoO2KqlILCO1dc6VPFecfUAZwQl9+Lad9GpFEeLbzqycN7Pf7DnJnVfREKoRB+RLT1IOo1UAFzv0xfgUePE+6O2B6+6bB/LFFCbPz3tHtlioYfXAHG9npiFHYpvBG8AJyfRq54oAJm6n5eHmazGCbxvt7HwGzgnoFo=,iv:CMMLaah1DcpHrLd1oWoKAOTPNwchkAlqMfJI0aYqEGs=,tag:p9pURiVC1DDtlm22RYInOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOTFjcG1UTXc1Z2pPZUlo
            Ly9XbjdYVjc1bVdpMlR1Q3cycVZlNS9ka2dvCjdCYXRPdXg0eHRnM2ExZUpnclNX
            UjV6LzZ6aVNySWJFaVdOVG5iMXNjZEUKLS0tIEkxUzJNS1hGV0U3SzB3VE8wQllO
            c2JyWEJFT1FBK3ZlbDFwRVZkN0NqU2cK5V4pgMf5OrCt1hQb3T54ociXe3+0AcRI
            ofhHnMFLcy96e5hH9R96qhRBzbQ660V2JwThsoR4ehui2Q5PX+L0Kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hux3h87h0480ss493kl292alfe6m6z5dhe76phvuk2c82hvg9clqmp6d8d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQXJnMnVIOEFZN3ZxNlA2
            YzBXYW9uQVhBZ256ZHdaYlNKT3dMTWNET1ZNCjhMczJKL0tXK3dIeXo1TVE1bWlM
            bU0yVXR4V3BnTG03U2FTSk9Hb1M3OHcKLS0tIGlCWHFWK1ljUnRUOEhndVB0OXQw
            RDBRdXBpRnVNNjYzdEtPZ2lIK3NVQ2MKbI+sJ+fHQvXQn5q8uyHYz7AwDDnifeu/
            8uyHqrQ/+bLrpED/xpsyaa9sGi2JHYrXNIZdbyOQWONcqICLZaqHPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZkptNTRqb09aVUVRM0N1
            bkxqbTBRck5aV25JM2V6aHBCZ0tMZ2xYT1U0Ci9WdURDMTR0SGptMjZIeEVPZHRt
            VjVwa1A3M0EvMkNmZnBwcGprZVo3d0UKLS0tIDZ5M2xnUFErYTNDOE1IUVFkdUhK
            NWlaVnZabVBSWit3ZnJYUVo2cUYxMmMKMG2A1UpQRqESG1t+H+xSIoJRwf39X/3W
            wWn4fqVQFBJAqDIZdbol0d4w5KniSMTPICZmOx/ArsZAMNUSbVrFjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18xn7rqxu27kschgqs7u5x7af9evnpcp4sru34th6zhhwlwnwycpsajeeh9
    lastmodified: "2026-07-30T09:03:41Z"
    mac: ENC[AES256_GCM,data:htjMpFhwXDgTSvv6ZzvUVLdKPisuDm1ky9Pal7Mevnn9BnzsvUHpVALl96RzTUJFofzezTZ1swc9fYS1dLGwCVE2gPV4bOSPlu3qdg2ULqbQYzmfW02eHZ/N4D/hMU+rZlhyKJbp7KIDifaqIb7iwXKW5ztYOSoeadeJIienZwM=,iv:V71vI5HpjAP8lhPFWnnpQGoNB2oKu9M2Lh72eHqMDhU=,tag:bq+LeE3VCX4tRZ+hguZe2Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
