sopsAgeKeys: ENC[AES256_GCM,data:NHOV0Ir2ek7LYohvFdYWZb8dbD4UUTjALIaIO/2DQnKHx9nJv01fSm7EuGOmR0x9uqk77CcW2BxNzWm9NpyG5AcaoY2PM2WFsTv/N1LKOvjVTqcejZaP692DdTOLcb1V2ucSYZUcqUXpq057h2LSr07PL9wJDr3yVjeZAF7hSjMYFW5Ipm8HHLWh9Z3Iwmq5+pOEclfbaReN0JbX8HWWJWkKm+m3vFu4mNJSiG7njVeq4h9JwMpfPNz/7Lw=,iv:YOO548M5Zh86ilU+BKjhS9SlUSu1FLolIDX/L3M+7Ls=,tag:2ljY08KVEjNYk32cX6X4Dg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUE44djRlVGF6SS9pU0pB
            Ui9rVzR5b3VFOXR6Y2Vaemprc2Jlem8wcmc4Cit4Zmd4QVpqbExVcFI0VWhZTmVO
            bWZnTGZKMUtIOEpydGJQbDJFcEY5c0EKLS0tIDI0cXVEbkJyWnk0Y3NoVGUrelFW
            U2NHSjg0djVlbDZLdElHVElSbTFRaWsK+aqNW/oNk1M0wbXnDWo6TBNI+ForTQ74
            QY3Vuhu6t6j82y7FYdd9+KVGRhBEXONtyHeBz1LpQkafvtiA34EBLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1svl2wxt9ej0g59k2tgcaclt457hf6kc5mnuw6926j8tydj08vfyqc4a8a8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxajYrMnVYaEZ1bGxHQUkr
            cE9zclpjRmZkdy9sQmdPUUVmL25LM3E5cFVJCjVQbmJLbE9KZTJxdEx5dTN5UzVB
            aW1pSE4wY1BkdmJPU2V2amcydzRmNW8KLS0tIHBaOU1HcklaSXJtMTdFU3N4MFFN
            N3VuS1d4R2xkL2JQSG9PUEUvK2RPamcKifPqVbalX0uGgNfsw9fKZGwXoGhG/0Z4
            dXmOYzcpdx3zH33I4J/uKVi+0Y6WbaXYX6PKCNvjZ3dY2b1wiGowOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bEMzQXozaXVDVWpvbGtE
            Vld5YzlYeEJBUWZZL0h4WXNuWnozMW1sM1ZZClhHNzF0aURHNGdTS0RWSHpsT2tx
            emE2UDRuOWNaZk9QMmE3VmpFMlh1NmMKLS0tIGpocjhKcWxRTmRVdmV6NGozZy9q
            QXQrUXk2RFNRTEhmZUxHNGhRMlhDYW8K+ItQyIWd9KHC1hRP2jAxxmzTWn2Y7tfC
            INXXKLrHHjrwVOUd2CMnwdljoPekF1se9tRWRUrc5lzAPLLMGZ2mgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18xn7rqxu27kschgqs7u5x7af9evnpcp4sru34th6zhhwlwnwycpsajeeh9
    lastmodified: "2026-08-19T06:32:13Z"
    mac: ENC[AES256_GCM,data:TVaKvEHnNZqMKvZjjYdvL5PqJbKWSuOHkbzmeWfe+Rc5zeqmbm7a3AhDM9eiSNvlhqUWTVpMphmdozaym7eorBFOFEDqE51Rd+Jk0tFZSGPCWFFv/U7chz+OMWr+f5li0j7qklwNhvGPo1B8yuTphfMLg9LN4oHIxIUYTt7nqF4=,iv:4k2DlmvPLQTlHQrHQxjfwvNfex3YIqMVGv+HBQciado=,tag:GjseQ1+Tax2GE0J/NDe0Ow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
