sopsAgeKeys: ENC[AES256_GCM,data:tGh7sG/dZ4iJvV787H1SfnMuDsp9174zQzPnHkpWMmdQQ2fpJ2+u2FV/lx4+1JJa49AXccpBht2n+dRY06HKPHHW3XO1gS0vsj6QQYegem/yIlez1QMNlOiIT0eZHonaQKQlUxUwr3aDZU9DIyAKTtjm95Bu6Cc4chr7dSoCuelVbzTn5P82jPrHxuSBf9zksLsVneRrtKy+VSnl5sV7tAS6t7p6peiVdlco9U1X6hM3WBiA7gR8Pfo67ac=,iv:LXhKpsKt3s2UKHUz5NLzI+9mrbn4Ui/Y1Pr1QUb33co=,tag:vX7vN0Qlbx744WD/pb9CpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WTVIZEJBSCtiYTF6eHA3
            ZTNVZkVwVWlDSU5udUJqYzk4aFBSQzZVSzJvCllUV1B3SHk4eWQwN25RNjN4d1JK
            TUJ0cFR3T0k5TUV4RHVqbkZITVVTMGMKLS0tIENuR2p3MmdpNEhXMUJYYUc0V0h0
            dFZyZWJVSVdGN0RRL20rRzR3ak5OazAK+my/30uNZpcZFwWSgYAjDSkyQpEmARTn
            5dDgjoRp3eYXCy0mBz6ZLPmNJf7j3avWTlyk2oNntXPy6kahJMk5qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1svl2wxt9ej0g59k2tgcaclt457hf6kc5mnuw6926j8tydj08vfyqc4a8a8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQTJ5SXhsOXdIN0NGQS9Z
            eVI4ZHN1Q3hCS2ViNnoxSFZkZDN1M0hsMEdrCldUaSs2YUMvZ1lyYWUyZVhSTDI5
            T1BmeVVURnNpeGszYkdwbzdDT09SS0kKLS0tIEtCa2xZZVl5elhpakZYY1pHQkRU
            RG03NEVlTmhzWU92K3dyYW1wT0dObUkK7QgpgPRiUWgueCR5PxV1haMVITMvEm/C
            ZbyAsElLFEfabIfsWJW6DJaQYzsb6UahfjS6RPURy7cCI5bpCGXfHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bzdvMEQ1TVdKS2ZGbC9k
            aFF3YmJYMTFzZkhFSFhRSmo4QlVjNUl2RWhnCnh2d1FSeVk4ZG9TYU1nQWVja2lw
            Y0dMNWJIUmJmU1BqUkpHQnY2LytYekEKLS0tIENZMFVIVlR0T1liNy9qQTIyb0dy
            SmFtY0ttMHc5MEY1NXNXcUJLWkI3K2MKvZBo7lvvBNTeLdgxhsVufIivsnFZF14U
            cJc+MxGX9mz3+rx03yY9x6imNVh3ENnH/h1Jd2+9nPdYvJdJi9wjeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18xn7rqxu27kschgqs7u5x7af9evnpcp4sru34th6zhhwlwnwycpsajeeh9
    lastmodified: "2026-08-21T11:50:39Z"
    mac: ENC[AES256_GCM,data:bZvGzIvdj6pgZtVsHPFPCRgRTs43ackNjkezkEEdt6szj1u+KJeFubI4wDa/ZpkNk5plKwZD7CgcdEkSAn85IJWu+jf15gJ3AdHeB4XO8mvEWDxRW6kmp56dcFATXDpUlD9c1WzO+caiyfgFEZ3SXPUKTz07tHZCPnb90OlEVAk=,iv:1wpQ6kUO+KJ1EvaBflV/5fIRXR+gSc+sPuuRP59E/LA=,tag:RaqMeSOSd+IKgQpMVzpBbA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
